# This is a basic workflow to help you get started with Actions

name: Ahoy

# Controls when the action will run. 
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Ahoy my Friend
        uses: Marta83/Ahoy-action@v2.1
        id: AhoyComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
